* Todo list as of May 23, 2018
[x] Make the toolbar swing into the empty space.
	This stopped working as soon as I checked it off.
	Changed to use min- and max-aspect-ratio instead.
	This worked fine on my desktop, but it fails on
	my phone, but it works on the phone simulator built
	into Chrome dev tools.  Checked with quirksmode.org
	and Chrome on my phone returns the same aspect-ratio
	in both landscape and portrait orientations.
[x] Make a Random class
[x] Move randomness into mahjong-app from mahjong-game.
[ ] Incorporate the mersenne-twister random number generator.
[ ] Finish cleaning up the svg coordinates.
[ ] Reimplement hot keys.
[ ] Implement tabIndex for traversing available moves.
[ ] Style the button focused outline to fit tiles.
[ ] Style the dialogs better.
[ ] Add the installtohomepage event handler and implementor.

  let deferredPrompt;
  window.addEventListener('beforeinstallprompt', (e) => {
    // Prevent Chrome 67 and earlier from automatically showing the prompt
    e.preventDefault();
    // Stash the event so it can be triggered later.
    deferredPrompt = e;
    // Update UI notify the user they can add to home screen
    btnAdd.style.display = 'block';
  });

  btnAdd.addEventListener('click', (e) => {
    // hide our user interface that shows our A2HS button
    btnAdd.style.display = 'none';
    // Show the prompt
    deferredPrompt.prompt();
    // Wait for the user to respond to the prompt
    deferredPrompt.userChoice
      .then((choiceResult) => {
        if (choiceResult.outcome === 'accepted') {
          console.log('User accepted the A2HS prompt');
        } else {
          console.log('User dismissed the A2HS prompt');
        }
        deferredPrompt = null;
      });
  });
[ ] figure out how to enable the tap gesture, though may be moot
    as click seems to work fine
